spring:
  datasource:
    driver-class-name: com.mysql.cj.jdbc.Driver
    username: root
    password: 1234
    url: jdbc:mysql://localhost:8080/test
  jpa:
    properties:
      hibernate:
        show_sql: true
        format_sql: true
